services:

  app:
    build: 
      context: .
      target: development
    container_name: Blog_App_Container
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      PORT: 8000
      REDIS_URL: redis://redis:6379
    command: npm run dev
    volumes: 
      - .:/app
      - app-node-modules:/app/node_modules
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: Blog_Redis_Container
    ports:
      - "6383:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  app-node-modules:
  redis-data:
