services:

  app:
    build: .
    container_name: Blog_App_Container
    ports:
     - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    
  redis:
    image: redis:7-alpine
    container_name: Blog_Redis_Container
    ports:
      - "6383:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis-data:/data

volumes:
  redis-data:




